#pragma once

#define RGBLIGHT_LED_COUNT 4

#define RGBLIGHT_LIMIT_VAL 120
#define RGBLIGHT_SLEEP

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGB_EFFECT_RAINBOW_SWIRL


#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7

#define OLED_DISPLAY_ADDRESS 0x3C
#define OLED_BRIGHTNESS 128
#define OLED_TIMEOUT 60000