#pragma once

#define RGB_LIMIT_VAL 120
#define RGBLIGHT_SLEEP

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7

#define OLED_DISPLAY_ADDRESS 0x3C
#define OLED_BRIGHTNESS 128
#define OLED_TIMEOUT 60000