#pragma once

#define WS2812_DI_PIN GP27
#define RGBLIGHT_LED_COUNT 4

#define RGBLIGHT_LIMIT_VAL 120
#define RGBLIGHT_SLEEP

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGB_EFFECT_RAINBOW_SWIRL