name: Build QMK firmware

on:
  push:
    paths:
      - "firmware/**"
      - ".github/workflows/build-qmk.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
      - name: Allow Git inside build container
        run: git config --global --add safe.directory '*'

      - name: Download QMK
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          submodules: recursive
          path: qmk_firmware

      - name: Download my Hackpad repository
        uses: actions/checkout@v4
        with:
          path: hackpad_repo

      - name: Copy my keyboard into QMK
        run: |
          mkdir -p qmk_firmware/keyboards/my_hackpad
          cp -R hackpad_repo/firmware/. qmk_firmware/keyboards/my_hackpad/

      - name: Compile firmware
        working-directory: qmk_firmware
        run: qmk compile -kb my_hackpad -km default

      - name: Save UF2 firmware
        uses: actions/upload-artifact@v4
        with:
          name: my-hackpad-firmware
          path: qmk_firmware/*.uf2
          if-no-files-found: error
